repos:
-   repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
      additional_dependencies: [flake8-bugbear]
      args: ["--show-source"]
-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
-   repo: local
    hooks:
    -   id: clang-format
        name: clang-format
        entry: clang-format
        language: system
        files: \.(c|cc|cxx|cpp|cu|h|hpp|hxx|cuh|proto)$
